// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpC5qji4q1J796YV87gAuKeJi0ItuwQlE',
    appId: '1:562825871063:web:ecb2c81b29a862cddf3a92',
    messagingSenderId: '562825871063',
    projectId: 'chat-app-29cb9',
    authDomain: 'chat-app-29cb9.firebaseapp.com',
    storageBucket: 'chat-app-29cb9.appspot.com',
    measurementId: 'G-66STRXTH3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZuUlYmhKsiorWgP6AQjiv7IHWuPHLzA',
    appId: '1:562825871063:android:5ae4bc9eb0e4d9bedf3a92',
    messagingSenderId: '562825871063',
    projectId: 'chat-app-29cb9',
    storageBucket: 'chat-app-29cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fSqX7_6KMUMqYJhaiuW-RAUdIYExonw',
    appId: '1:562825871063:ios:a20a79c16cbcdc54df3a92',
    messagingSenderId: '562825871063',
    projectId: 'chat-app-29cb9',
    storageBucket: 'chat-app-29cb9.appspot.com',
    iosClientId: '562825871063-67ncnabh8ltoui9kedhttm2cr8nhccfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fSqX7_6KMUMqYJhaiuW-RAUdIYExonw',
    appId: '1:562825871063:ios:a20a79c16cbcdc54df3a92',
    messagingSenderId: '562825871063',
    projectId: 'chat-app-29cb9',
    storageBucket: 'chat-app-29cb9.appspot.com',
    iosClientId: '562825871063-67ncnabh8ltoui9kedhttm2cr8nhccfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
